#!/usr/bin/env python

import sys
import sqlite3
import subprocess

executables = ["ls", "date"]



def main(args):
  if len(args) != 2:
    print "usage:"
    exit (1)
  
  for executable in executables:
    try:
      out, err = subprocess.Popen([executable], stdout = subprocess.PIPE,
        stderr = subprocess.PIPE).communicate()
    except OSError:
      print "Can't find " + executable + " execuatble"
      exit(1)


def createTable(cursor):
  pass


if __name__ == "__main__":
  main(sys.argv)
