#!/usr/bin/env python

import sys
import subprocess
import re
import os

executables = ["ls", "date"]



def main(args):
  if len(args) != 2:
    print "usage:"
    exit (1)
  
  for executable in executables:
    try:
      out, err = subprocess.Popen([executable], stdout = subprocess.PIPE,
        stderr = subprocess.PIPE).communicate()
    except OSError:
      print "Can't find " + executable + " execuatble"
      exit(1)
  
  match = re.match('(.*)\.(.*)', os.path.basename(args[1]))
  if not (match):
    print "unrecognised extension"
    exit (1)
  pathAbs = args[1]
  if not os.path.isabs(pathAbs):
    pathAbs = os.path.join(os.getcwd(), pathAbs)
  outputName = os.path.join(os.getcwd(), match.group(1)) + ".mp4"
  if os.path.normpath(pathAbs) == (outputName):
    outputName = os.path.join(os.getcwd(), match.group(1)) + "_converted.mp4"
  print outputName


def createTable(cursor):
  pass


if __name__ == "__main__":
  main(sys.argv)
